/**
 * GENERATED — do not edit. Produced by `pnpm sync:core` from
 * `src/generated/prisma/enums.ts`, which Prisma writes from schema.prisma.
 *
 * This is the shared domain vocabulary. Re-exporting the generated file rather
 * than hand-maintaining a copy is what stops the web app and the mobile app
 * ever disagreeing about what `PAID` means.
 */
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TenantStatus = {
  ONBOARDING: 'ONBOARDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED'
} as const

export type TenantStatus = (typeof TenantStatus)[keyof typeof TenantStatus]


export const TenantRole = {
  OWNER: 'OWNER',
  STAFF: 'STAFF'
} as const

export type TenantRole = (typeof TenantRole)[keyof typeof TenantRole]


export const StorefrontTheme = {
  CLASSIC: 'CLASSIC',
  EDITORIAL: 'EDITORIAL',
  UTILITY: 'UTILITY'
} as const

export type StorefrontTheme = (typeof StorefrontTheme)[keyof typeof StorefrontTheme]


export const PlatformRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SUPPORT: 'SUPPORT'
} as const

export type PlatformRole = (typeof PlatformRole)[keyof typeof PlatformRole]


export const OrderStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const CouponType = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED'
} as const

export type CouponType = (typeof CouponType)[keyof typeof CouponType]


export const DeliveryMethod = {
  PICKUP: 'PICKUP',
  ZONE_DELIVERY: 'ZONE_DELIVERY',
  COURIER_API: 'COURIER_API'
} as const

export type DeliveryMethod = (typeof DeliveryMethod)[keyof typeof DeliveryMethod]


export const PaymentProvider = {
  PAYSTACK: 'PAYSTACK',
  FLUTTERWAVE: 'FLUTTERWAVE'
} as const

export type PaymentProvider = (typeof PaymentProvider)[keyof typeof PaymentProvider]


export const WebhookStatus = {
  RECEIVED: 'RECEIVED',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
  IGNORED: 'IGNORED'
} as const

export type WebhookStatus = (typeof WebhookStatus)[keyof typeof WebhookStatus]
